# Generated by Django 5.1.5 on 2025-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='name',
        ),
        migrations.AddField(
            model_name='zone',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
