# Generated by Django 5.1.5 on 2025-01-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_zone_name_zone_coordinates_delete_coordinate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
