# Generated by Django 5.1.5 on 2025-01-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='zone',
        ),
    ]
