# Generated by Django 5.1.5 on 2025-01-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_feedback_feedback_text_alter_feedback_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
    ]
