# Generated by Django 5.1.5 on 2025-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_feedback_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='d7180276-21a1-44fc-8db0-5486ad9f05d0', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
