# Generated by Django 5.1.5 on 2025-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_feedback_feedback_id_feedback_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='75fbff29-07b1-4c8c-93c8-250d188f0abe', max_length=255, unique=True),
        ),
    ]
