# Generated by Django 5.1.5 on 2025-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_feedback_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='a5028d79-0a85-48dd-863b-19d816374f02', max_length=255, unique=True),
        ),
    ]
