# Generated by Django 5.1.5 on 2025-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_feedback_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='813a3f49-e313-482b-9698-d8f8fbe364b3', max_length=255, unique=True),
        ),
    ]
