# Generated by Django 5.1.5 on 2025-01-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_feedback_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='5be11dc3-aa69-45d9-91cd-49c9e7b48cb0', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
    ]
