# Generated by Django 5.1.5 on 2025-01-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_feedback_feedback_id_alter_feedback_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='f64d0a4d-259c-4b3d-b6bf-a2daaca33e54', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
    ]
