# Generated by Django 5.1.5 on 2025-01-22 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_feedback_feedback_id_alter_feedback_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(default='d21f40ed-3994-4e87-9a5f-e9c4a408d19d', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
