# Generated by Django 5.1.5 on 2025-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_feedback_feedback_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='comment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='zone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
